memodir = "~/ghq/github.com/w40141/vault/Memo"
memotemplate = "$XDG_CONFIG_HOME/memo/templates/md.txt"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
assetsdir = "."
pluginsdir = "$XDG_CONFIG_HOME/memo/plugins"
