tap "argon/mas"
tap "aws/tap"
tap "beeftornado/rmtree"
tap "brona/iproute2mac"
tap "buo/cask-upgrade"
tap "delphinus/sfmono-square"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "k1low/tap"
tap "ktr0731/evans"
tap "michaeleisel/zld"
tap "mongodb/brew"
tap "neovim/neovim"
tap "noborus/tap"
tap "teamookla/speedtest"
tap "tgotwig/linux-dust"
brew "act"
brew "adns"
brew "aom"
brew "asdf"
brew "aspell"
brew "atk"
brew "autoconf"
brew "automake"
brew "aws/tap/copilot-cli"
brew "awscli"
brew "bandwhich"
brew "bat"
brew "bdw-gc"
brew "bingrep"
brew "boost"
brew "bottom"
brew "bzip2"
brew "cairo"
brew "cask"
brew "ccls"
brew "cffi"
brew "cheat"
brew "circleci"
brew "cmake"
brew "cmake-docs"
brew "cmatrix"
brew "composer"
brew "convmv"
brew "coreutils"
brew "csview"
brew "curl"
brew "dash"
brew "doggo"
brew "duf"
brew "dust"
brew "efm-langserver"
brew "eigen"
brew "emacs"
brew "ethereum"
brew "eza"
brew "faac"
brew "fd"
brew "fdk-aac"
brew "fish"
brew "fontconfig"
brew "freetype"
brew "freexl"
brew "fribidi"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gd"
brew "gdk-pixbuf"
brew "geos"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "gibo"
brew "giflib"
brew "git"
brew "git-delta"
brew "git-secrets"
brew "glib"
brew "gmp"
brew "gnupg"
brew "gnutls"
brew "go"
brew "gobject-introspection"
brew "golangci-lint"
brew "gping"
brew "graphite2"
brew "graphviz"
brew "grex"
brew "gsettings-desktop-schemas"
brew "gtk+"
brew "gtk+3"
brew "guile"
brew "hadolint"
brew "harfbuzz"
brew "hexyl"
brew "hicolor-icon-theme"
brew "ht"
brew "httpie"
brew "hugo"
brew "icarus-verilog"
brew "icu4c"
brew "imagemagick"
brew "isl"
brew "jemalloc"
brew "jq"
brew "json-c"
brew "k1low/tap/tbls"
brew "ktr0731/evans/evans"
brew "kubernetes-cli"
brew "lame"
brew "libassuan"
brew "libbluray"
brew "libcaca"
brew "libdnet"
brew "libepoxy"
brew "libevent"
brew "libffi"
brew "libgcrypt"
brew "libgpg-error"
brew "libheif"
brew "libidn2"
brew "libksba"
brew "libmpc"
brew "libogg"
brew "libpng"
brew "libpq"
brew "librsvg"
brew "libssh2"
brew "libtasn1"
brew "libtermkey"
brew "libtool"
brew "libunistring"
brew "libusb"
brew "libuv"
brew "libvorbis"
brew "libvpx"
brew "libxslt"
brew "libzip"
brew "little-cms2"
brew "llvm"
brew "lua-language-server"
brew "luajit"
brew "luarocks"
brew "mongodb/brew/mongodb-community"
brew "mongosh"
brew "mpfr"
brew "msgpack"
brew "mysql-client"
brew "navi"
brew "ncurses"
brew "neovim"
brew "nettle"
brew "nkf"
brew "noborus/tap/trdsql"
brew "npth"
brew "nsh"
brew "nspr"
brew "nss"
brew "oniguruma"
brew "openjpeg"
brew "openssl@3"
brew "opus"
brew "p11-kit"
brew "p7zip"
brew "pacvim"
brew "pandoc"
brew "pango"
brew "pastel"
brew "pcre"
brew "pcre2"
brew "pdm"
brew "peco"
brew "perl"
brew "php"
brew "pinentry"
brew "pipx"
brew "pixman"
brew "pkg-config"
brew "pnpm"
brew "poppler"
brew "procs"
brew "proj"
brew "protobuf"
brew "pycparser"
brew "readline"
brew "redis"
brew "rig"
brew "ripgrep"
brew "rtmpdump"
brew "rustup-init"
brew "sdl2"
brew "shared-mime-info"
brew "silicon"
brew "snappy"
brew "solana"
brew "solidity"
brew "sox"
brew "sqlite"
brew "sqlite-utils"
brew "starship"
brew "stylua"
brew "subversion"
brew "swftools"
brew "tbb"
brew "tcl-tk"
brew "tealdeer"
brew "teamookla/speedtest/speedtest"
brew "terraform"
brew "theora"
brew "tmux"
brew "toilet"
brew "tokei"
brew "tree"
brew "tree-sitter"
brew "trivy"
brew "unar"
brew "unibilium"
brew "unzip"
brew "vim"
brew "vimpager"
brew "w3m"
brew "watchexec"
brew "webp"
brew "wget"
brew "x265"
brew "xinput"
brew "xsv"
brew "xvid"
brew "xz"
brew "zellij"
brew "zeromq"
brew "zlib"
brew "zoxide"
cask "alfred"
# Web browser focusing on privacy
cask "brave-browser"
# Clipboard extension app
cask "clipy"
cask "color-oracle"
# Universal database tool and SQL client
cask "dbeaver-community"
# Trains AIs to understand and translate texts
cask "deepl"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Online diagram software
cask "drawio"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-biz-udgothic"
# Universal design typeface in the Japanese Mincho type tradition
cask "font-biz-udmincho"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Japanese programming font which is a composed of Hack and GenJyuu-Gothic
cask "font-hackgen"
# Japanese programming font which is a composed of Hack and GenJyuu-Gothic
cask "font-hackgen-nerd"
cask "font-noto-sans-cjk"
# Font editor and converter for outline and bitmap fonts
cask "fontforge"
# Git client focusing on productivity
cask "gitkraken"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Japanese input software
cask "google-japanese-ime"
# Utility to fix grammar errors and style issues in text
cask "grammarly"
# Screenshot and screen recording tool
cask "gyazo"
# IDE for Java development - community edition
cask "intellij-idea-ce"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Interface for reading and syncing eBooks
cask "kindle"
# Software for Logitech devices
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Japanese input software
cask "google-japanese-ime"
# Utility to fix grammar errors and style issues in text
cask "grammarly"
# Screenshot and screen recording tool
cask "gyazo"
# IDE for Java development - community edition
cask "intellij-idea-ce"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Interface for reading and syncing eBooks
cask "kindle"
# Software for Logitech devices
cask "logi-options-plus"
# Full TeX Live distribution without GUI applications
cask "mactex-no-gui"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# App to write, plan, collaborate, and get organized
cask "notion"
# Collaboration platform for API development
cask "postman"
# MySQL/MariaDB database management
cask "sequel-ace"
# PDF reader and note-taking application
cask "skim"
# Video chat, voice call and instant messaging application
cask "skype"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Development environment
cask "vagrant"
# Open-source code editor
cask "visual-studio-code"
# Web browser with built-in email client focusing on customization and control
cask "vivaldi"
# Video communication and virtual meeting platform
cask "zoom"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Mathpix Snipping Tool", id: 1349670778
mas "NanoBrowser", id: 1440590513
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TweetDeck", id: 485812721
mas "Xcode", id: 497799835
