tap "ariga/tap"
tap "beeftornado/rmtree"
tap "brona/iproute2mac"
tap "buo/cask-upgrade"
tap "delphinus/sfmono-square"
tap "neovim/neovim"
tap "reviewdog/tap"
tap "sonatype-nexus-community/nancy-tap"
tap "teamookla/speedtest"
brew "act"
brew "adns"
brew "bzip2"
brew "giflib"
brew "ncurses"
brew "libffi"
brew "zlib"
brew "libpng"
brew "xz"
brew "little-cms2"
brew "openssl@3"
brew "readline"
brew "unzip"
brew "webp"
brew "aom"
brew "libtool"
brew "aspell"
brew "pcre2"
brew "glib"
brew "at-spi2-core"
brew "perl"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bandwhich"
brew "libssh2"
brew "oniguruma"
brew "bat"
brew "bdw-gc"
brew "bingrep"
brew "boost"
brew "bottom"
brew "freetype"
brew "fontconfig"
brew "pixman"
brew "cairo"
brew "gmp"
brew "coreutils"
brew "libevent"
brew "libunistring"
brew "libidn2"
brew "libtasn1"
brew "nettle"
brew "p11-kit"
brew "gnutls"
brew "tree-sitter"
brew "emacs"
brew "cask"
brew "llvm"
brew "ccls"
brew "pycparser"
brew "cffi"
brew "cheat"
brew "circleci"
brew "cmake"
brew "cmake-docs"
brew "cmatrix"
brew "cmigemo"
brew "rtmpdump"
brew "curl"
brew "gd"
brew "libgpg-error"
brew "libgcrypt"
brew "libxslt"
brew "libzip"
brew "php"
brew "composer"
brew "convmv"
brew "copilot"
brew "csview"
brew "dagger"
brew "dash-shell"
brew "doggo"
brew "duf"
brew "dust"
brew "efm-langserver"
brew "eigen"
brew "eksctl"
brew "ethereum"
brew "evans"
brew "eza"
brew "faac"
brew "fd"
brew "fdk-aac"
brew "fish"
brew "libogg"
brew "mesa"
brew "freexl"
brew "fribidi"
brew "fzf"
brew "mpfr"
brew "gawk"
brew "isl"
brew "libmpc"
brew "gcc"
brew "shared-mime-info"
brew "gdk-pixbuf"
brew "geos"
brew "gh"
brew "graphite2"
brew "harfbuzz"
brew "openjpeg"
brew "pango"
brew "ghostscript"
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-secrets"
brew "glow"
brew "libassuan"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "go"
brew "go-task"
brew "pkgconf"
brew "gobject-introspection"
brew "golangci-lint"
brew "gpgme"
brew "gping"
brew "librsvg"
brew "graphviz"
brew "grex"
brew "grype"
brew "gsettings-desktop-schemas"
brew "hicolor-icon-theme"
brew "gtk+"
brew "libepoxy"
brew "xkeyboard-config"
brew "gtk+3"
brew "guile"
brew "hadolint"
brew "hexyl"
brew "ht"
brew "httpie"
brew "hugo"
brew "icarus-verilog"
brew "x265"
brew "libheif"
brew "imagemagick"
brew "iperf"
brew "jemalloc"
brew "jq"
brew "json-c"
brew "kind"
brew "kubernetes-cli"
brew "lame"
brew "libbluray"
brew "libcaca"
brew "libdnet"
brew "libvorbis"
brew "opus"
brew "unibilium"
brew "libtermkey"
brew "libuv"
brew "libvpx"
brew "luajit"
brew "mermaid-cli"
brew "minikube"
brew "mise"
brew "mosquitto"
brew "msgpack"
brew "mysql-client"
brew "navi"
brew "neovim"
brew "nkf"
brew "nsh"
brew "nspr"
brew "nss"
brew "openjdk"
brew "osv-scanner"
brew "p7zip"
brew "pacvim"
brew "pandoc"
brew "pastel"
brew "pcre"
brew "pdm"
brew "peco"
brew "poppler"
brew "procs"
brew "proj"
brew "protobuf"
brew "redis"
brew "rig"
brew "ripgrep"
brew "rustup"
brew "sdl2"
brew "selene"
brew "snappy"
brew "solidity"
brew "sonar-scanner"
brew "sox"
brew "sqlite-utils"
brew "starship"
brew "stern"
brew "subversion"
brew "swftools"
brew "syft"
brew "tbb"
brew "tbls"
brew "tcl-tk"
brew "tealdeer"
brew "tflint"
brew "theora"
brew "tmux"
brew "todo-txt"
brew "toilet"
brew "tokei"
brew "tree"
brew "trivy"
brew "typos-cli"
brew "unar"
brew "uv"
brew "vim"
brew "vimpager"
brew "w3m"
brew "watchexec"
brew "wget"
brew "xvid"
brew "zellij"
brew "zeromq"
brew "zoxide"
brew "ariga/tap/atlas"
brew "reviewdog/tap/reviewdog"
brew "sonatype-nexus-community/nancy-tap/nancy"
brew "teamookla/speedtest/speedtest"
# cask "alfred"
# # Web browser focusing on privacy
# cask "brave-browser"
# # Clipboard extension app
# cask "clipy"
# cask "color-oracle"
# # Universal database tool and SQL client
# cask "dbeaver-community"
# # Trains AIs to understand and translate texts
# cask "deepl"
# # Voice and text chat software
# cask "discord"
# # App to build and share containerized applications and microservices
# cask "docker"
# # Online diagram software
# cask "drawio"
# # Collaborative team software
# cask "figma"
# # Web browser
# cask "firefox"
# cask "font-biz-udgothic"
# # Universal design typeface in the Japanese Mincho type tradition
# cask "font-biz-udmincho"
# # Developer targeted fonts with a high number of glyphs
# cask "font-hack-nerd-font"
# cask "font-hackgen"
# # Japanese programming font which is a composed of Hack and GenJyuu-Gothic
# cask "font-hackgen-nerd"
# cask "font-noto-sans-cjk"
# # Font editor and converter for outline and bitmap fonts
# cask "fontforge"
# # Git client focusing on productivity
# cask "gitkraken"
# # Web browser
# cask "google-chrome"
# # Client for the Google Drive storage service
# cask "google-drive"
# # Interface for reading and syncing eBooks
# cask "kindle"
# # Client for the Google Drive storage service
# cask "google-drive"
# # Japanese input software
# cask "google-japanese-ime"
# # Utility to fix grammar errors and style issues in text
# cask "grammarly"
# # Screenshot and screen recording tool
# cask "gyazo"
# # IDE for Java development - community edition
# cask "intellij-idea-ce"
# # Terminal emulator as alternative to Apple's Terminal app
# cask "iterm2"
# # Software for Logitech devices
# cask "logi-options-plus"
# # Full TeX Live distribution without GUI applications
# cask "mactex-no-gui"
# # Provides updates to various Microsoft products
# cask "microsoft-auto-update"
# # Office suite
# cask "microsoft-office"
# # App to write, plan, collaborate, and get organized
# cask "notion"
# # Collaboration platform for API development
# cask "postman"
# # MySQL/MariaDB database management
# cask "sequel-ace"
# # PDF reader and note-taking application
# cask "skim"
# # Video chat, voice call and instant messaging application
# cask "skype"
# # Team communication and collaboration software
# cask "slack"
# # Music streaming service
# cask "spotify"
# # Development environment
# cask "vagrant"
# # Open-source code editor
# cask "visual-studio-code"
# # Web browser with built-in email client focusing on customization and control
# cask "vivaldi"
# # Video communication and virtual meeting platform
# cask "zoom"
# mas "Amphetamine", id: 937984704
# mas "GarageBand", id: 682658836
# mas "iMovie", id: 408981434
# mas "Keynote", id: 409183694
# mas "LINE", id: 539883307
# mas "Magnet", id: 441258766
# mas "Mathpix Snipping Tool", id: 1349670778
# mas "NanoBrowser", id: 1440590513
# mas "Numbers", id: 409203825
# mas "Pages", id: 409201541
# mas "TweetDeck", id: 485812721
# mas "Xcode", id: 497799835
