version: "2"
linters:
  # Default set of linters.
  # The value can be:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  # default: standard
  #   - errcheck
  #   - govet
  #   - ineffassign
  #   - staticcheck
  #   - unused
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq -r '.[] | select(.fast==true) | "-\(.name)"'`).
  default: fast
  #   -asciicheck
  #   -bidichk
  #   -copyloopvar
  #   -cyclop
  #   -decorder
  #   -depguard
  #   -dogsled
  #   -dupl
  #   -dupword
  #   -funcorder
  #   -funlen
  #   -gocheckcompilerdirectives
  #   -gochecknoinits
  #   -gocognit
  #   -gocyclo
  #   -godot
  #   -godox
  #   -goheader
  #   -mnd
  #   -gomoddirectives
  #   -gomodguard
  #   -goprintffuncname
  #   -grouper
  #   -inamedparam
  #   -ineffassign
  #   -interfacebloat
  #   -lll
  #   -maintidx
  #   -misspell
  #   -nakedret
  #   -nestif
  #   -nlreturn
  #   -nosprintfhostport
  #   -prealloc
  #   -predeclared
  #   -promlinter
  #   -tagalign
  #   -testableexamples
  #   -testpackage
  #   -usestdlibvars
  #   -whitespace
  #   -wsl
  #   -nolintlint
  # default: all
  # Enable specific linter.
  enable:
    - revive
    - wsl_v5
  disable:
    # Go linter that checks if package imports are in a list of acceptable packages.
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    # Check if comments end in a period.
    - godot
    - gochecknoinits
    - gosmopolitan
    # - inamedparam
    # - nlreturn
    - tagliatelle
    - varnamelen
    # - wsl
  settings:
    # https://golangci-lint.run/usage/linters/#linters-configuration
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
        - NOTE
        - OPTIMIZE
        - HACK
    revive:
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      enable-all-rules: true
      rules:
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#add-constant
        - name: add-constant
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - max-lint-count: "3"
              allow-strs: ""
              allow-ints: "0,1,2,3"
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#line-length-limit
        - name: line-length-limit
          severity: warning
          disabled: false
          exclude: [""]
          arguments: [100]
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      # Excluding configuration per-path, per-linter, per-text and per-source.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
formatters:
  # https://golangci-lint.run/usage/configuration/#formatters-configuration
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    warn-unused: true
    generated: strict
issues:
  # https://golangci-lint.run/usage/configuration/#issues-configuration
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
# output:
# https://golangci-lint.run/usage/configuration/#output-configuration
run:
  # https://golangci-lint.run/usage/configuration/#run-configuration
  timeout: 5m
severity:
  # https://golangci-lint.run/usage/configuration/#severity-configuration
  default: error
