filters: {}
rules:
  preset-ja-technical-writing: true
  preset-ja-spacing: true
  preset-jtf-style: true
  terminology:
    defaultTerms: true
  prh:
    rulePaths:
      - '~/.local/share/mise/installs/node/20.6.1/lib/node_modules/prh/prh-rules/media/WEB+DB_PRESS.yml'
