filters:
rules:
  preset-smarthr: true
  # preset-bengo4: true
  # preset-ja-technical-writing: true
  # preset-japanese: true
  # preset-ja-technical-writing: true
  # preset-ja-spacing: true
  # preset-jtf-style: true
  # terminology:
  #   defaultTerms: true
  prh:
    rulePaths:
      - /home/linuxbrew/.linuxbrew/lib/node_modules/prh-rules/media/WEB+DB_PRESS.yml
