[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
let g:dein#plugin.build = 'make'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

[[plugins]]
repo = 'dracula/vim'
hook_add = '''
set background=dark
autocmd MyAutoCmd VimEnter * nested colorscheme dracula
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle']
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/nerdtree.rc.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
rev = 'release'
merged = '0'
hook_source = '''
source $XDG_CONFIG_HOME/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
let g:UltiSnipsExpandTrigger='<C-g>'
let g:UltiSnipsJumpForwardTrigger="<C-f>"
let g:UltiSnipsJumpBackwardTrigger="<C-b>"
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tyru/caw.vim'
on_map = [['nx', '<Plug>']]
hook_add = '''
" 行の最初の文字の前にコメント文字をトグル
nmap gcc <Plug>(caw:hatpos:toggle)
vmap gcc <Plug>(caw:hatpos:toggle)
" 行頭にコメントをトグル
nmap gc, <Plug>(caw:zeropos:toggle)
vmap gc, <Plug>(caw:zeropos:toggle)
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'
depends = ['webapi-vim']

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = 'Gitv'
depends = ['vim-fugitive']

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/nerdtree-git-plugin.rc.vim
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']

[[plugins]]
repo = 'vimtaku/hl_matchit.vim.git'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

# toDo
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_source = '''
let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
