[[plugins]]
repo = 'Shougo/dein.vim'
hook_post_update = '''
function s:dein_cleanup() abort
	echo '[dein] Removing disabled plugins...'
	call map(dein#check_clean(), "delete(v:val, 'rf')")
	call dein#recache_runtimepath()
	echohl WarningMsg
	echo '[dein] Successfully removed disabled plugins'
	echohl None
endfunction
command DeinCleanUp call s:dein_cleanup()
	'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'dracula/vim'
hook_add = '''
autocmd MyAutoCmd VimEnter * nested colorscheme dracula
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle']
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/nerdtree.rc.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
rev = 'release'
merged = '0'
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']

[[plugins]]
repo = 'vimtaku/hl_matchit.vim.git'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

# toDo
[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# toDo
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['latex']
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
