[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'
on_if = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
hook_source = 'source $XDG_CONFIG_HOME/nvim/plugins/unite.rc.vim'
hook_add = '''
nnoremap [unite] <Nop>
nmap ,u [unite]
nnoremap <silent> [unite]f :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
nnoremap <silent> [unite]B :<C-u>Unite buffer_tab -buffer-name=file<CR>
nnoremap <silent> [unite]r :<C-u>Unite register<CR>
nnoremap <silent> [unite]m :<C-u>Unite file<CR>
nnoremap <silent> [unite]c :<C-u>Unite bookmark<CR>
nnoremap <silent> [unite]o :<C-u>Unite outline<CR>
nnoremap <silent> [unite]t :<C-u>Unite tab<CR>
nnoremap <silent> [unite]w :<C-u>Unite window<CR>
'''

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'
hook_add = '''
nnoremap <silent> <Space>uo   :<C-u>Unite -no-quit -vertical -winwidth=30 outline<CR>
'''

#   " vimfiler {{{
#   "https://github.com/Shougo/vimfiler.vim
#   NeoBundleLazy "Shougo/vimfiler", {
#         \ "depends": ["Shougo/unite.vim"],
#         \ "autoload": {
#         \   "commands": ['VimFilerTab',
#         \                'VimFiler',
#         \                'VimFilerExplorer',
#         \                'VimFilerBufferDir'],
#         \   "mappings": ['<Plug>(vimfiler_switch)'],
#         \   "explorer": 1,
#         \ }}
#   "現在開いているバッファをIDE風に開く
#   nnoremap <silent> <Leader>e :<C-u>VimFilerBufferDir -split -simple -winwidth=35 -no-quit<CR>
#   " nnoremap <Leader>e :VimFilerExplorer<CR>
#   " close vimfiler automatically when there are only vimfiler open
#   autocmd MyAutoCmd BufEnter * if (winnr('$') == 1 && &filetype ==# 'vimfiler') | q | endif
#   let s:hooks = g:neobundle#get_hooks('vimfiler')
#   function! s:hooks.on_source(bundle)
#     let g:vimfiler_as_default_explorer = 1
#     let g:vimfiler_enable_auto_cd = 1
#
#     " .から始まるファイルおよび.pycで終わるファイルを不可視パターンに
#     let g:vimfiler_ignore_pattern = '\%(^\..*\|\.pyc$\)'
#
#     " vimfiler specific key mappings
#     autocmd MyAutoCmd FileType vimfiler call s:vimfiler_settings()
#     function! s:vimfiler_settings()
#       " ^^ to go up
#       nmap <buffer> ^^ <Plug>(vimfiler_switch_to_parent_directory)
#       " use R to refresh
#       nmap <buffer> R <Plug>(vimfiler_redraw_screen)
#       " overwrite C-l
#       nmap <buffer> <C-l> <C-w>l
#     endfunction
#   endfunction
#   " 保留 {{{
#   " " Edit file by tabedit.
#   " let g:vimfiler_edit_action = 'edit'
#   " " Like Textmate icons.
#   " let g:vimfiler_tree_leaf_icon = ' '
#   " let g:vimfiler_tree_opened_icon = '▾'
#   " let g:vimfiler_tree_closed_icon = '▸'
#   " let g:vimfiler_file_icon = '-'
#   " let g:vimfiler_marked_file_icon = '*'
#   " nmap <F2>  :VimFiler -split -horizontal -project -toggle -quit<CR>
#   " autocmd FileType vimfiler nnoremap <buffer><silent>/  :<C-u>Unite file -default-action=vimfiler<CR>
#   " autocmd FileType vimfiler nnoremap <silent><buffer> e :call <SID>vimfiler_tree_edit('open')<CR>
#   "
#   " function! s:vimfiler_tree_edit(method)
#   "   " let file = vimfiler#get_file()
#   "   " if empty(file) || empty(a:method) | return | endif
#   "   " let path = file.action__path
#   "   " wincmd p
#   "   " execute a:method
#   "   " exe 'edit' path
#   "   if empty(a:method) | return | endif
#   "   let linenr = line('.')
#   "   let context = s:vimfiler_create_action_context(a:method, linenr)
#   "   wincmd p
#   "   " call vimfiler#mappings#do_action(a:method, linenr)
#   "   call context.execute()
#   "   unlet context
#   " endfunction
#   "
#   " function! s:vimfiler_create_action_context(action, ...)
#   "   let cursor_linenr = get(a:000, 0, line('.'))
#   "   let vimfiler = vimfiler#get_current_vimfiler()
#   "   let marked_files = vimfiler#get_marked_files()
#   "   if empty(marked_files)
#   "     let marked_files = [ vimfiler#get_file(cursor_linenr) ]
#   "   endif
#   "
#   "   let context = s:vimfiler_context.new({
#   "          'action' : a:action,
#   "          'files' : marked_files,
#   "          'current_dir' : vimfiler.current_dir,
#   "          })
#   "   return context
#   " endfunction
#   "
#   " let s:vimfiler_context = {}
#   " function! s:vimfiler_context.new(...)
#   "   let dict = get(a:000, 0, {})
#   "   return extend(dict, self)
#   " endfunction
#   "
#   " function! s:vimfiler_context.execute()
#   "   call unite#mappings#do_action(self.action, self.files, {
#   "          'vimfiler__current_directory' : self.current_dir,
#   "          })
#   " endfunction
#   "}}}
#   " }}}

[[plugins]]
repo = 'Shougo/vimshell'
on_map = [['n', '<Plug>']]
hook_add = 'nmap [Space]s  <Plug>(vimshell_switch)'
# hook_source = 'source $XDG_CONFIG_HOME/nvim/plugins/vimshell.rc.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'Shougo/unite-sudo'

[[plugins]]
repo = 'Kocha/vim-unite-tig'

[[plugins]]
repo = 'osyo-manga/unite-vimpatches'

[[plugins]]
repo = 'Shougo/unite-build'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'sorah/unite-ghq'
on_source = 'unite.vim'

