[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
if dein#util#_is_windows()
  let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
  let cmd = 'make -f make_cygwin.mak'
elseif executable('gmake')
  let cmd = 'gmake'
else
  let cmd = 'make'
endif
let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

[[plugins]]
repo = 'dracula/vim'
hook_add = '''
set background=dark
autocmd MyAutoCmd VimEnter * nested colorscheme dracula
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle']
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/nerdtree.rc.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
rev = 'release'
merged = '0'
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'
depends = ['webapi-vim']

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = 'Gitv'
depends = ['vim-fugitive']

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree']
hook_add = '''
source $XDG_CONFIG_HOME/nvim/plugins/nerdtree-git-plugin.rc.vim
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']

[[plugins]]
repo = 'vimtaku/hl_matchit.vim.git'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n nzz<Plug>(anzu-update-search-status)
nmap N Nzz<Plug>(anzu-update-search-status)
nmap * <Plug>(anzu-star-with-echo)
nmap # <Plug>(anzu-sharp-with-echo)
" clear status
nmap <C-c><C-c> <Plug>(anzu-clear-search-status) :<C-u>nohlsearch<cr><Esc>
" set statusline=%{anzu#search_status()}
'''

# toDo
[[plugins]]
repo = 'majutsushi/tagbar'

# toDo
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
