[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'itchyny/landscape.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'croaker/mustang-vim'

[[plugins]]
repo = 'jnurmine/Zenburn'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'mrkn/mrkn256.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'therubymug/vim-pyte'

[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'rhysd/vim-color-spring-night'

[[plugins]]
repo = 'alessandroyorba/alduin'
[[plugins]]
repo = 'Haron-Prime/Antares'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = '0xcharly/vim-frictionless'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# [[plugins]]
# repo = 'bcicen/vim-vice' 

hook_add = '''
" 4
" colorscheme iceberg
" 3.5
" colorscheme moonshine
" 4
" colorscheme hybrid
" 3
" colorscheme mustang
" 4
" colorscheme Zenburn
" 3.5
" colorscheme lucius
" 3.5
" colorscheme mrkn256
" 3
" colorscheme jellybeans
" 2
" colorscheme monokai
" 2
" colorscheme badwolf
" 4
if !has('nvim')
	colorscheme railscasts
endif
" 4
" colorscheme Apprentice
" 4
" colorscheme tender
" 3
" colorscheme kalisi
" 2
" colorscheme pencil
" 5
" colorscheme spring-night
if has('nvim')
	colorscheme dracula
endif
" 2
" colorscheme Alduin
" 4
" colorscheme Antares
" 3
" colorscheme seoul256
" 3.5
" colorscheme frictionless
"
" colorscheme one
"
" colorscheme vice

autocmd MyAutoCmd ColorScheme * highlight LineNr ctermfg=80
set background=dark

'''

