[[plugins]]
repo = 'tyru/caw.vim'
on_map = [['nx', '<Plug>']]
hook_add = '''
	" 行の最初の文字の前にコメント文字をトグル
	nmap gcc <Plug>(caw:hatpos:toggle)
	vmap gcc <Plug>(caw:hatpos:toggle)
	" 行頭にコメントをトグル
	nmap gc, <Plug>(caw:zeropos:toggle)
	vmap gc, <Plug>(caw:zeropos:toggle)
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = [['nv', '<Plug>']]
hook_add = '''
	" disable netrw's gx mapping.
	let g:netrw_nogx = 1
	nmap gx <Plug>(openbrowser-smart-search)
	vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'AndrewRadev/switch.vim'
on_cmd = 'Switch'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = [['nx', '<Plug>']]
hook_add = '''
	nmap p <Plug>(yankround-p)
	xmap p <Plug>(yankround-p)
	nmap P <Plug>(yankround-P)
	nmap gp <Plug>(yankround-gp)
	xmap gp <Plug>(yankround-gp)
	nmap gP <Plug>(yankround-gP)
	nmap yp <Plug>(yankround-prev)
	nmap yn <Plug>(yankround-next)
	"" 履歴取得数
	let g:yankround_max_history = 50
	""履歴一覧(kien/ctrlp.vim)
	nnoremap <silent>g<C-c> :<C-u>CtrlPYankRound<CR>
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugin]]
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
on_map = [['n', '<Plug>']]
hook_add = '''
	" saiw(
	nmap <silent>sa <Plug>(operator-surround-append)
	" sda(
	nmap <silent>sd <Plug>(operator-surround-delete)
	" sra"'
	nmap <silent>sr <Plug>(operator-surround-replace)
	" カーソル位置から一番近い括弧を削除する
	nmap <silent>sdd <Plug>(operator-surround-delete)<Plug>(textobj-multiblock-a)
	" カーソル位置から一番近い括弧を変更する
	nmap <silent>srr <Plug>(operator-surround-replace)<Plug>(textobj-multiblock-a)
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3']

[[plugins]]
repo = 'fisadev/vim-isort'
on_ft = ['python', 'python3']
hook_add = '''
	let g:vim_isort_map = '<C-i>'
	let g:vim_isort_python_version = 'python3'
'''

[[plugins]]
repo = 'Integralist/vim-mypy'
on_ft = ['python', 'python3']

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = [['n', '<Plug>']]
hook_add = '''
	nmap <Space>m <Plug>(quickhl-manual-this)
	xmap <Space>m <Plug>(quickhl-manual-this)
	nmap <Space>M <Plug>(quickhl-manual-reset)
	xmap <Space>M <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'troydm/easybuffer.vim'
on_cmd = 'EasyBuffer'
hook_add = 'nnoremap buf :<C-u>EasyBuffer<CR>'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = [['n', '<Plug>']]
hook_add = 'nmap <Leader>qr <Plug>(quickrun)'
hook_post_source = '''
	let g:quickrun_config = {'*': {'runner': 'remote/vimproc'}, }
	let g:quickrun_config={'*': {'split': 'vertical'}}
	set splitright
'''

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = 'GundoToggle'
hook_add = '''
	nnoremap <Leader>g :GundoToggle<CR>
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'
depends = ['webapi-vim']

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = 'Gitv'
depends = ['vim-fugitive']

[[plugins]]
repo = 'reireias/vim-cheatsheet'
on_cmd = 'Cheat'
hook_source = '''
	let g:cheatsheet#cheat_file = './util/cheatsheet.md'
'''

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
	source $XDG_CONFIG_HOME/nvim/plugins/vimtex.rc.vim
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd', 'md']
hook_add = '''
	let g:vim_markdown_frontmatter = 1
	let g:vim_markdown_math = 1
	let g:vim_markdown_conceal = 0
'''

[[plugins]]
repo = 'kazuph/previm'	
on_ft = ['markdown', 'mkd', 'md']
hook_source = '''
	nnoremap <silent><Leader><Leader>o :PrevimOpen<CR>
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown', 'txt']
hook_add = '''
	let g:table_mode_corner = '|'
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ["html", "html5"]
hook_source = '''
	source $XDG_CONFIG_HOME/nvim/plugins/emmet.rc.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_source = '''
  call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': ['latex', 'tex']})
  call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': ['latex', 'tex']})
  call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': ['latex', 'tex']})
'''

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = '''has('nvim')'''
# # on_event = 'InsertCharPre'
# on_event = 'InsertEnter'
# depends = ['context_filetype.vim']
# hook_source = 'let g:deoplete#enable_at_startup = 1'
# hook_post_source = 'source $XDG_CONFIG_HOME/nvim/plugins/deoplete.rc.vim'
