-- -- On ly required if you have packer in your `opt` pack
-- local install_path = vim.fn.stdpath("data").."/site/pack/packer/start/packer.nvim"
-- if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
--   packer_bootstrap = vim.fn.system({"git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", install_path})
-- end
--
-- require("packer").startup(function(use)
--   use "wbthomason/packer.nvim"
--   use 'kyazdani42/nvim-web-devicons'
--   use({ "rcarriga/nvim-notify", module = "notify" })
--   -- use({
--   --     "folke/todo-comments.nvim",
--   --     event = "VimEnter",
--   --     config = function()
--   --         require("rc/pluginconfig/todo-comments")
--   --     end,
--   -- })
--
--   if packer_bootstrap then
--     require("packer").sync()
--   end
-- end)
-- vim.cmd([[autocmd BufWritePost init.lua source <afile> | PackerCompile]])
--
-- local on_attach = function(client, bufnr)
--     local function buf_set_keymap(...)
--         vim.api.nvim_buf_set_keymap(bufnr, ...)
--     end
-- end
