-- Enter ex-commands in a nice floating input.
-- https://github.com/VonHeikemen/fine-cmdline.nvim

-- vim.api.nvim_set_keymap('n', '<CR>', '<cmd>FineCmdline<CR>', {noremap = true})
-- vim.api.nvim_set_keymap('n', ':', '<cmd>FineCmdline<CR>', {noremap = true})
-- require('fine-cmdline').setup({
--     cmdline = {
--         enable_keymaps = true,
--         smart_history = true
--     },
--     popup = {
--         position = {
--             row = '10%',
--             col = '50%',
--         },
--         size = {
--             width = '60%',
--             height = 1
--         },
--         border = {
--             style = 'rounded',
--             highlight = 'FloatBorder',
--         },
--         win_options = {
--             winhighlight = 'Normal:Normal',
--         },
--     },
--     hooks = {
--         before_mount = function(input)
--             -- Prompt can influence the completion engine.
--             -- This is your chance to change it to something that works for you
--             input.input_props.prompt = ': '
--         end,
--         after_mount = function(input)
--             -- code
--         end,
--         set_keymaps = function(imap, feedkeys)
--             local fn = require('fine-cmdline').fn
--             imap('<M-k>', fn.up_search_history)
--             imap('<M-j>', fn.down_search_history)
--             imap('<Up>', fn.up_history)
--             imap('<Down>', fn.down_history)
--         end
--     }
-- })
