[tools]
python = "3.12.1"
deno = "1.40.3"
bun = "1.0.26"
erlang = "26.2.1"
elixir = "1.16.1-otp-26"
kotlin = "1.9.22"
ruby = "3.3.4"
elm = "0.19.1"
gradle = "3.5.1"
java = "corretto-8.202.08.2"
node = "20.6.1"
usage = "latest"
zig = "latest"
gleam = "latest"
dotnet = "8.0.303"
