[tools]
deno = "latest"
bun = "1.0.26"
elixir = "1.16.1-otp-26"
kotlin = "1.9.22"
ruby = "3.3.4"
elm = "0.19.1"
gradle = "3.5.1"
java = "corretto-8.202.08.2"
node = "20.6.1"
usage = "latest"
zig = "latest"
python = "3.12.6"
erlang = "latest"
gleam = "1.5.0"
lua = "5.1.5"
dotnet = "8.0.402"
dotnet-core = "8.0.402"
