[tools]
deno = "2.2.10"
bun = "1.0.26"
elixir = "1.18.2-otp-27"
ruby = "3.3.4"
elm = "0.19.1"
gradle = "3.5.1"
java = "corretto-8.202.08.2"
node = "23.11.0"
usage = "latest"
zig = "latest"
erlang = "27.2.2"
gleam = "1.5.0"
lua = "5.1.5"
dotnet = "8.0.402"
dotnet-core = "8.0.402"
python = "3.12.2"
# kotlin = "latest"
