[tools]
python = "3.11.6"
pnpm = "latest"
deno = "latest"
bun = "latest"
erlang = "latest"
elixir = "latest"
kotlin = "latest"
ruby = "3.3.0"
elm = "latest"
gradle = "latest"
java = "latest"
node = "20.6.1"
